spring:
  application:
    name: discovery-service

eureka:
  cliente:
    eureka-server-connect-timeout-seconds: 5
    enabled: true
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8761
